### ISSUE TITLE
Replace DAO's block/level counter with a regular estimate timer

### ISSUE THREAD

**Issue by namesty** [dOrgTech/homebase-app#247]
## Overview

It's much easier to tell users how much time is remaining from current cycle in terms of days/hours/minutes. We want to display time like this for the user but the internal calculations the app does should still be expressed in blocks/levels.

## Suggested Approach

- Current block fetching is being done here: `src/services/bakingBad/context/TZKTSubscriptions.tsx`
- Should be as simple as adding an additional `timeEstimateForNextBlock` to the `CycleInfo` object. By using `https://tzstats.com/docs/api#blockchain-config` we can get the current `time between blocks` approximate in seconds. We would then multiply this by the number of blocks left in the cycle.

## Tasks

- [x] Calculate remaining time with API call to TzStats
- [x] Display approximate time in the UI with a timer component
- [x] Keep the level/block counter in smaller text as reference
