### ISSUE TITLE
FAQ page implementation

### ISSUE THREAD

**Issue by namesty** [dOrgTech/homebase-app#249]
## Overview

We need to have an FAQ page to show the information contained [here](https://docs.google.com/document/d/1IZKbAQ3L-RpMcxLHzfqhcsX888DTHhDX83RgCSPg-z8/edit). This information should be presented in the nice rich text format that documents have, but should abide by our app's theme rules.

## Tasks

- [x] Create FAQ page with dynamic items for each question and its answer
- [x] Render FAQ text as markdown, probably using a doc -> markdown converter and a react markdown npm package compatible with material UI
- [x] Design is here: https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase-(Copy)?node-id=3882%3A520

**Comment by namesty** [comment]
Under `src/modules/home` there are already some components implemented (very WIP) under `faq-impl` branch @juliopavila
